import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google"
import { LangProvider } from "@/context/useLang";


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  return (
    <html lang="en">
      <LangProvider>
        <body
          className={`${poppins.variable} bg-[#111111] w-screen h-screen overflow-x-hidden`}
        >
          {children}
        </body>
      </LangProvider>
    </html>
  );
}
